name: Automatic Version Bump with Commitizen

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0



    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'



    - name: Install uv (optional)
      run: |
        pip install --upgrade pip uv

    - name: Install Commitizen and cz-changeup explicitly
      run: |
        pip install commitizen cz-changeup


    - name: Run version bump and create tag (Commitizen)
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        NEXT_TAG=$(cz bump --get-next 2>&1) || true
        if echo "$NEXT_TAG" | grep -q '\[NO_COMMITS_TO_BUMP\]'; then
          echo "::notice::No eligible commits for bump. Exiting successfully."
          exit 0
        fi
        NEXT_TAG="v$NEXT_TAG"
        git tag -d "$NEXT_TAG" || true
        cz bump --yes


    - name: Push changes and tags
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD:main
        git push origin --tags